name: Rewatchables on Netflix

on:
  # Trigger every Tuesday at 10:10 AM
  schedule:
    - cron: "10 10 * * 2"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: TMDB

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag rewatchables:$(date +%s)
      run: docker build . --file Dockerfile --tag rewatchables:0.0.1
      env: 
         TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    - name: Run the Docker image
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: docker run rewatchables:0.0.1
